### ISSUE TITLE
Same UUID generated by processes started at precisely the same time

### ISSUE THREAD

**Issue by mgsloan** [aslatter/uuid#16]
This causes spurious errors in a test-suite which spawns numerous processes.  I don't see a very direct way to use the UUID library in a way that reliably generates unique identifiers.  Perhaps the implementation should be changed to handle this circumstance?

Repro steps: 

0. Have a fast computer?  Might not repro for everyone.
1. `git clone https://github.com/mgsloan/uuid-v4-collision-repro.git`
2. `stack build`
3. `stack exec uuid-v4-collision-repro-exe-2`

Results:

```
...
Iteration #143
766fd3c5-b3d9-4df4-b845-a6ae45c0a903
766fd3c5-b3d9-4df4-b845-a6ae45c0a903
uuid-v4-collision-repro-exe-2: UUID collision!
```

**Comment by aslatter** [comment]
"Technically" you can use any random source implementing the `RandomGen` class from the `random` package. I don't know if any exist that are high-enough quality.

I'm guessing that the right thing to do would be to use something like `Data.Random.Source.DevRandom` from the `random-source` package, and use that to pull values from `/dev/urandom`.

**Comment by mgsloan** [comment]
Right, I guess the issue is that using something from the UUID package gives some impression that you'll get UUIDs which have the property that collisions are extremely improbable.  #15 points out a different flaw with using `StdGen`.

Pulling values from `/dev/urandom` is quite a lot slower than using pseudo random numbers.  Also, this would cause issues with windows support.  I think the ideal thing would look like:

* Initialize a global pseudorandom number generator based on data from urandom / mac address / current time / process id / thread id.
* Use `atomicModifyIORef` to update the prng state and get a random value.  Possibly use [mwc-random](http://hackage.haskell.org/package/mwc-random) ?

Then, the `nextRandom` can either be deprecated, or its meaning can change (major version bump).  The advantage of changing the meaning is that uses of it are atomatically "fixed" and we don't need to come up with another name.  The advantage of deprecating is that someone might rely on it using the current `StdGen`, for deterministic

Seems worthwhile to have some package which provides a global PRNG which gets properly initialized.

**Comment by jsermeno** [comment]
Looks like this has since been fixed in https://github.com/aslatter/uuid/commit/bd60ffec647a3b446c87f79452deea4a1221442b. Thanks for the commit @aslatter. It's really useful.

**Comment by mgsloan** [comment]
Awesome!!
