### ISSUE TITLE
toText / fromText

### ISSUE THREAD

**Issue by wereHamster** [aslatter/uuid#4]
The `text` package doesn't have any crazy dependencies, and since you already depend on `bytestring` it isn't too crazy to support `text` as well.

**Comment by BardurArantsson** [comment]
Does `text` ship with GHC, though? (Is it part of `base`?)

**Comment by aslatter** [comment]
It's in the Haskell Platform.

**Comment by BardurArantsson** [comment]
Yes, but at least some Linux distributions (Arch Linux in my case) don't ship the HP as such. Of course they do have packages for 'text', but in my experience it's much simpler to only install GHC + cabal-install from the distro and use sandboxes for everything.

**Comment by aslatter** [comment]
Hey @wereHamster - should `toText`/`fromText` be for the strict or lazy `Text` variant? I know we should probably support both, but I wasn't sure which should have the "most privileged" name.

**Comment by wereHamster** [comment]
Whatever type is provided by `Data.Text`, because that's what most people use.
